spring:
  cloud:
    function:
      definition: producer
    stream:
      bindings:
        producer-out-0:
          destination: demo-topic # multiple topics can be specified as comma separated values
        ping-out:
          destination: topic-1

      kafka:
        binder:
          brokers: localhost:9092
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
      poller:
        fixed-delay: 1000
  