spring:
  cloud:
    function:
      definition: paymenConsumer
    stream:
      bindings:
        paymenConsumer-in-0:
          destination: payment-events # multiple topics can be specified as comma separated values
          group: demo-group
      kafka:
        binder:
          brokers: localhost:9092
          consumer-properties:
            auto.offset.reset: earliest
  